from .pathology import *
from .pathology_draft import *
from .speciality import *
from .substance import *
from .association import *
from .therapeutic_class import *
from .user import *
from .page import *
from .news import *
