FROM node:8.11-alpine

MAINTAINER Courtel Eliot <eliot.courtel@wanadoo.fr>
WORKDIR /home/app/front

RUN apk update
RUN apk add git

ENTRYPOINT npm install && ./node_modules/bower/bin/bower install --allow-root && ./node_modules/gulp/bin/gulp.js templates;
